### ISSUE TITLE
train 2D Xnet question

### ISSUE THREAD

**Issue by Ystartff** [Yanfeng-Zhou/XNet#18]
Hello! I would like to know how your mean and std are calculated if training other datasets, because I see that in semi-supervised learning, the unlabelled and labelled files contain L and H files.

**Comment by Ystartff** [comment]
Hello, my problem is that when I do onehot coding the previous batches target.shape is (2,128,128,2) but the later batches have (2,128,128,256). A problem with the code prompts me to
Traceback (most recent call last):
  File "train_semi_XNet.py", line 255, in <module>
    loss_train_sup1 = criterion(pred_train_sup1, mask_train_sup)
  File "/home/panxue/anaconda3/envs/wave/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/panxue/PX/XNet-main/loss/loss_function.py", line 132, in forward
    return self._base_forward(output, target_one_hot, valid_mask)
  File "/mnt/data/panxue/PX/XNet-main/loss/loss_function.py", line 100, in _base_forward
    dice_loss = dice(predict[:, i], target[..., i], valid_mask)
IndexError: index 2 is out of bounds for dimension 1 with size 2
Traceback (most recent call last):
  File "train_semi_XNet.py", line 255, in <module>
    loss_train_sup1 = criterion(pred_train_sup1, mask_train_sup)
  File "/home/panxue/anaconda3/envs/wave/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/panxue/PX/XNet-main/loss/loss_function.py", line 132, in forward
    return self._base_forward(output, target_one_hot, valid_mask)
  File "/mnt/data/panxue/PX/XNet-main/loss/loss_function.py", line 100, in _base_forward
    dice_loss = dice(predict[:, i], target[..., i], valid_mask)
IndexError: index 2 is out of bounds for dimension 1 with size 2

**Comment by Yanfeng-Zhou** [comment]
Hello!
1. I have written the corresponding code for the calculation of mean and std, but have not uploaded it. I will consider updating the code. In fact, the calculation of mean and std is very simple: calculate the mean and standard deviation of the individual pixel values of all images in the training data.
2. **IndexError: index 2 is out of bounds for dimension 1 with size 2**. This error most likely comes from you not processing the mask (the foreground pixel in the mask before processing is 255). For binary semantic segmentation problems, the foreground pixel in the mask should be 1.

**Comment by Ystartff** [comment]
Thank you author for your previous help, but I followed your method with my mask. but on the fifteenth round of display the problem appeared
Traceback (most recent call last):
  File "train_semi_XNet.py", line 294, in <module>
    train_eval_list1, train_eval_list2, train_m_jc1, train_m_jc2 = print_train_eval_XNet(cfg['NUM_CLASSES'], score_list_train1, score_list_train2, mask_list_train, print_num_half)
  File "/mnt/data/panxue/PX/XNet-main/config/train_test_config/train_test_config.py", line 106, in print_train_eval_XNet
    eval_list1 = evaluate(score_list_train1, mask_list_train)
  File "/mnt/data/panxue/PX/XNet-main/config/eval_config/eval.py", line 25, in evaluate
    jaccard[indy] = tp / float(union + tp)
ZeroDivisionError: float division by zero
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1938996 closing signal SIGTERM
