### ISSUE TITLE
The size of tensor a (16384) must match the size of tensor b (49152) at non-singleton dimension 1

### ISSUE THREAD

**Issue by HHDAW** [Yanfeng-Zhou/XNet#25]
Hello，thanks for your great work.I had some problems before the model training started.I tried to adjust the image but it didn't work.Please give me some advice.The following is the error message
Traceback (most recent call last):
  File "/root/autodl-tmp/XNET/XNet-main/XNet-main/train_semi_XNet.py", line 254, in <module>
    loss_train_sup1 = criterion(pred_train_sup1, mask_train_sup)
  File "/root/miniconda3/envs/xnet3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/XNET/XNet-main/XNet-main/loss/loss_function.py", line 119, in forward
    return self._base_forward(output, target_one_hot, valid_mask)
  File "/root/autodl-tmp/XNET/XNet-main/XNet-main/loss/loss_function.py", line 92, in _base_forward
    dice_loss = dice(predict[:, i], target[..., i], valid_mask)
  File "/root/miniconda3/envs/xnet3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/XNET/XNet-main/XNet-main/loss/loss_function.py", line 59, in forward
    num = torch.sum(torch.mul(predict, target) * valid_mask, dim=1) * 2 + self.smooth
RuntimeError: The size of tensor a (16384) must match the size of tensor b (49152) at non-singleton dimension 1

**Comment by HHDAW** [comment]
Yes.I read the previous question.But I use the /config/augmentation/online_aug.py to resize the image,it still reports errors.

**Comment by Yanfeng-Zhou** [comment]
Can you print **pred_train_sup1.shape** and **mask_train_sup.shape**.  There are some problems with the first dimension of these two tensors.

**Comment by HHDAW** [comment]
pred_train_sup1.shape([2, 2, 128, 128])  and  mask_train_sup.shape ([2, 128, 128, 3, 256])

**Comment by Yanfeng-Zhou** [comment]
The shape of your mask is very strange. Generally speaking, for 2D images, the image shape is [B, C, H, W] while the mask shape is [B, H, W]. what is the meaning of "3" and "256" in your mask shape.

**Comment by HHDAW** [comment]
I changed my image  ,but report error 
Traceback (most recent call last):
  File "/root/autodl-tmp/XNET/XNet-main/XNet-main/train_semi_XNet.py", line 255, in <module>
    loss_train_sup1 = criterion(pred_train_sup1, mask_train_sup)
  File "/root/miniconda3/envs/xnet3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/XNET/XNet-main/XNet-main/loss/loss_function.py", line 122, in forward
    target_one_hot = F.one_hot(torch.clamp_min(target, 0))
RuntimeError: CUDA out of memory. Tried to allocate 25.75 GiB (GPU 0; 23.70 GiB total capacity; 5.48 GiB already allocated; 16.48 GiB free; 5.54 GiB reserved in total by PyTorch)

**Comment by HHDAW** [comment]
Sorry，I have one more question to ask.
Why is the model with the best results printed out not saved during training,Saved results are less than optimal

**Comment by HHDAW** [comment]
Sorry，I have one more question to ask.
During training,Why is my best printed data inconsistent with my saved model.Saved results are less than optimal
